wireservice/csvkit

docs/tutorial/3_power_tools.rst

A few changes to Lesson 3

---

csvkit/grep.py
tests/test_grep.py

As it turns out, there was a bug! (but no one ever hit it because any_match isn't exposed).

Add test for FilteringCSVReader with any_match argument, closes #89

---

docs/tutorial/1_getting_started.rst
docs/tutorial/2_examining_the_data.rst
docs/tutorial/3_power_tools.rst

A couple of fixes for its/it's, and my text editor removed some trailing line spaces.

Minor grammar fix for tutorial docs.

---

docs/scripts/sql2csv.rst

[#352] Add SQLAlchemy encoding to documentation

---

csvkit/utilities/csvgrep.py

The implementation is copied from `csvcut`.

Add `--no-header-row` option for csvgrep. Closes #254 #279.

---

tests/test_utilities/test_sql2csv.py

I suppose we can merge this to avoid any regression.

Add test related to #440

---

requirements-py2.txt
requirements-py3.txt
setup.py

Remove openpyxl and xlrd dependencies

---

csvkit/utilities/csvsort.py

Blocked by https://github.com/onyxfish/agate/issues/454

Convert csvsort to agate, closes #495

---

csvkit/table.py
csvkit/utilities/csvsql.py
csvkit/utilities/csvstat.py
csvkit/utilities/in2csv.py

Wait for #551, as the errors are in CSVSort.

Use sniff_limit internally instead of snifflimit

---

CHANGELOG
csvkit/utilities/csvjson.py
tests/test_utilities/test_csvjson.py

csvjson streams input and output if the --stream and --no-inference flags are set

---

docs/scripts/csvlook.rst

Mention less -S tip in csvlook page

---

CHANGELOG
csvkit/convert/geojs.py
csvkit/utilities/in2csv.py
examples/test_geojson.csv
tests/test_utilities/test_in2csv.py

closes #185
@onyxfish You opened #185, so can you review whether the output conforms to expectations?

in2csv GeoJSON conversion adds columns for geometry type, longitude and latitude

---

CHANGELOG
csvkit/utilities/csvlook.py
docs/scripts/csvlook.rst
tests/test_utilities/test_csvlook.py

Add --max-rows, --max-columns and --max-column-width options

---

csvkit/cli.py
csvkit/utilities/csvjson.py
csvkit/utilities/csvlook.py
csvkit/utilities/csvsort.py

Evolution of #638.
Closes #596.

Attempt partial fix to PY2 encoding errors

---

csvkit/utilities/csvsql.py
csvkit/utilities/sql2csv.py

csvsql: Output a header row in all cases, like other utilities

---

csvkit/cli.py
csvkit/utilities/csvjson.py
tests/test_utilities/test_csvclean.py
tests/test_utilities/test_csvjson.py
tests/test_utilities/test_sql2csv.py
tests/utils.py

Use try/finally instead of closing files in tests when errors are raised

---

csvkit/cli.py
csvkit/utilities/csvsort.py
tests/test_convert/test_fixed.py
tests/test_utilities/test_csvclean.py
tests/test_utilities/test_csvformat.py
tests/test_utilities/test_csvjson.py
tests/test_utilities/test_csvlook.py
tests/test_utilities/test_csvsort.py
tests/test_utilities/test_csvsql.py
tests/test_utilities/test_in2csv.py
tests/test_utilities/test_sql2csv.py
tests/utils.py

Close all opened files in tests, to test whether agate closes them early

---

csvkit/utilities/csvstat.py
docs/index.rst
docs/scripts/csvclean.rst
docs/scripts/csvformat.rst
docs/scripts/csvgrep.rst
docs/scripts/csvjoin.rst
docs/scripts/csvjson.rst
docs/scripts/csvsort.rst
docs/scripts/csvsql.rst
docs/scripts/csvstat.rst
docs/scripts/in2csv.rst
docs/tricks.rst
docs/tutorial/2_examining_the_data.rst
docs/tutorial/3_power_tools.rst

Tidy and make minor updates to documentation

---

CHANGELOG.rst
csvkit/utilities/csvpy.py
docs/scripts/csvpy.rst

csvpy: Add support for --agate to read a CSV file into an agate table

---

docs/scripts/csvclean.rst

I'm not sure csvclean doesn't clean more than what I wrote. Feel free to complete.

Better documentation

---

docs/scripts/csvclean.rst

Reverts wireservice/csvkit#753

Revert "Better documentation"

---

docs/tutorial/3_power_tools.rst

I noticed display issues when reading the docs; this should fix them.

Fix code blocks

---

docs/scripts/csvgrep.rst

Update docs to include way to use csvgrep to search for all rows that do not have an empty cell.

Update docs for csvgrep

---

CHANGELOG.rst
csvkit/utilities/csvstat.py
tests/test_utilities/test_csvstat.py

csvstat adds a --freq-count option to set the maximum number of frequent values to display

---

CHANGELOG.rst
csvkit/utilities/sql2csv.py
docs/scripts/sql2csv.rst
examples/test.sql
examples/test_latin1.sql
tests/test_utilities/test_sql2csv.py

sql2csv adds an encoding option to specify the encoding of the input query file

---

CHANGELOG.rst
csvkit/utilities/csvsql.py

csvsql: Add an --overwrite flag

---

csvkit/utilities/csvstack.py
tests/test_utilities/test_csvstack.py

csvstack: Add --skip-lines support

---

CHANGELOG.rst
csvkit/utilities/in2csv.py

in2csv: Fix piping an Excel file

---

docs/common_arguments.rst

-L should be -K after ceedd14868fe50f974590ac8674e1db25c5b9be3

fix docs for common arguments

---

docs/common_arguments.rst

Corrected the --skip-lines parameter from -L to -K in the Common Arguments documentation.

Corrected the --skip-lines parameter from -L to -K

---

README.rst

We've been offering SVG badges for shields.io for several years now. :-)

Use SVG badges instead of PNG

---

CHANGELOG.rst
csvkit/utilities/in2csv.py
docs/scripts/csvclean.rst
docs/scripts/csvcut.rst
docs/scripts/csvformat.rst
docs/scripts/csvgrep.rst
docs/scripts/csvjoin.rst
docs/scripts/csvjson.rst
docs/scripts/csvlook.rst
docs/scripts/csvpy.rst
docs/scripts/csvsort.rst
docs/scripts/csvsql.rst
docs/scripts/csvstack.rst
docs/scripts/csvstat.rst
docs/scripts/in2csv.rst
docs/scripts/sql2csv.rst

in2csv supports --no-header-row on XLS and XLSX files

---

CHANGELOG.rst
csvkit/utilities/csvsql.py
docs/release.rst
setup.py
tests/test_utilities/test_csvsql.py

Add tests to #865

---

CHANGELOG.rst
csvkit/utilities/csvjson.py
tests/test_utilities/test_csvjson.py

Add commits to #867

---

csvkit/utilities/csvstat.py

guard format_decimal() from formatting infinities

---

AUTHORS.rst
CHANGELOG.rst
csvkit/cli.py
csvkit/utilities/csvsql.py
csvkit/utilities/csvstat.py
csvkit/utilities/in2csv.py
csvkit/utilities/sql2csv.py
docs/common_arguments.rst
docs/contributing.rst
docs/scripts/csvclean.rst
docs/scripts/csvsql.rst
docs/scripts/csvstack.rst
docs/tricks.rst
docs/tutorial/1_getting_started.rst
docs/tutorial/2_examining_the_data.rst
docs/tutorial/3_power_tools.rst
docs/tutorial/4_going_elsewhere.rst
tests/test_utilities/test_csvcut.py
tests/test_utilities/test_csvsql.py
tests/test_utilities/test_in2csv.py

Tidy #955 and miscellaneous fixes

---

.github/workflows/ci.yml
docs/contributing.rst
setup.py

https://pythoninsider.blogspot.com/2021/10/python-3100-is-available.html

Add Python 3.10 to the testing

---

csvkit/utilities/csvsql.py

Hi jpmckinney,
I hope this is what you need. Thank you for your effort.
Best,
Stefan/ badbunnyyy

Feature: csvsql: specify --query multiple times #1160

---

csvkit/cleanup.py
csvkit/cli.py
csvkit/convert/fixed.py
csvkit/convert/geojs.py
csvkit/grep.py
csvkit/utilities/csvclean.py
csvkit/utilities/csvformat.py
csvkit/utilities/csvjson.py
csvkit/utilities/csvpy.py
csvkit/utilities/csvsql.py
csvkit/utilities/csvstat.py
csvkit/utilities/in2csv.py
docs/conf.py
tests/test_utilities/test_csvclean.py

- converted some strings to f-strings
- simplified a conditional
- replaced unreliable hasattr(ob, __call) with callable(obj)
- removed unnecessary brackets

language updates including f-strings and more reliable callable() function

---

CHANGELOG.rst
csvkit/cleanup.py
csvkit/cli.py
csvkit/utilities/csvclean.py
docs/scripts/csvclean.rst
tests/test_utilities/test_csvclean.py

csvclean: Use standard output and standard error, and use exit code 1 if errors #781 #195

---

.github/workflows/ci.yml
csvkit/utilities/in2csv.py

- **ci: Add stdin tests**
- **ci: Add pipe tests**

Add pipe tests

---

CHANGELOG.rst
csvkit/cli.py
csvkit/utilities/csvsql.py
csvkit/utilities/sql2csv.py

Adds `--engine-option` to `csvsql`. Similar to previous work in sql2csv to accommodate unique database configurations.

Adds --engine-option to `csvsql`.

---

.github/workflows/ci.yml
csvkit/cli.py
docs/common_arguments.rst

Use PYTHONIOENCODING if set (--encoding takes priority)
