csvkit/cli.py
tests/test_utilities/test_csvgrep.py

This fixes an issue where utilities without the `--no-header-row` option (such as csvgrep) throw an AttributeError when run with the `--names` option.
Using `getattr` with a default value of `None` shouldn't have any other consequences, since if `no_header_row` is missing from the `argparse.Namespace` object, there can't be a conflict between `--names` and  `--no-header-row`.
This fixes #254 and #279. The same problem is mentioned in #399, but I believe this is a more complete fix.
Also added a test for the `--names` flag.

fixed AttributeError with -n argument for utils with -H suppressed

---

docs/tutorial/1_getting_started.rst

there was a NICAR thread where someone new to python was trying to use this tutorial, and copy pasted an entire line, including the `$`. google doesn't recognize `$` so search results for `$: command not found` aren't helpful. this is a common issue for python beginners.
makes me sad to think of all the new folks who might be missing out on the wonders of csvkit, b/c this getting started tutorial isn't copy/paste friendly! here's an easy fix.

remove $ for more beginner friendly docs

---

docs/index.rst

I noticed a typo in `docs/index.rst`: "matching ells" => "matching cells"
(PS: Thanks for making `csvkit`, it's awesome!)

Small typo in the docs

---

csvkit/utilities/in2csv.py

It looks like in2csv was just using the wrong kwarg.
Changed --no-inference to set infer_types like table.py does, not type_inference.

Fix #379 in2csv --no-inference use infer_types

---

csvkit/utilities/csvstack.py
tests/test_utilities/test_csvstack.py

Original issue reported on #414. Came across same need while running csvstack on automated jenkins jobs and went for the fix, having not seen strong reasons why it cannot accept single files. Added couple of basic tests testing basic csvstack functionality with one file and with multiple files.
Closes #414

csvstack accepts single file without errors

---

docs/scripts/in2csv.rst

Technically, in2csv accepts CSV input, but it's much more useful if fed some other format ;)

correct in2csv docs

---

AUTHORS
CHANGELOG
csvkit/sql.py
docs/install.rst
tests/test_sql.py

Closes #455 
Also removes support for dialects that have since been dropped from SQLAlchemy. See http://docs.sqlalchemy.org/en/latest/dialects/

Add support for custom SQLAlchemy dialects

---

csvkit/utilities/csvjson.py
tests/test_utilities/test_csvjson.py

@onyxfish As with #538, please review the changes to the tests (having to do with type inference) to see if this is the desired new behavior. If so, we'll need to document the changes in the changelog.

csvjson: Use agate.Table.to_json(), closes #539

---

CHANGELOG
csvkit/utilities/csvsort.py
tests/test_utilities/test_csvsort.py

Instead of using a `lambda` in the `order_by` in csvkit, we could now delegate this to agate. However, csvkit's rule for `None` was that it is less than everything, but in agate, `None` is greater than everything. Would this be a breaking change, or can we change the rule?
/cc @onyxfish 
Also, note that this PR may fail until agate is released with https://github.com/wireservice/agate/pull/607 merged.

Simplify (and speed up) the sorting call to agate

---

csvkit/cli.py
csvkit/utilities/csvjson.py
csvkit/utilities/csvlook.py
csvkit/utilities/csvsort.py
csvkit/utilities/in2csv.py

csvlook: Fix "underlying stream is not seekable" when piping input

---

docs/tutorial/1_getting_started.rst

Small suggestion for tutorial: show the user how to view a wide table using `less -S`, without needing to extract columns first.

Recommend `less -S` for viewing wide tables

---

tests/utils.py

Closes #696.
@onyxfish Not sure if the `warnings.filterwarnings` line is in the best place.

Ignore warnings about unspecified column names from agate in tests

---

csvkit/cli.py
csvkit/utilities/csvjson.py

Closes #732 
The issue was that we would double encode files.

Fix output encoding error in Python 2

---

csvkit/utilities/csvpy.py

I'm getting issues like this, though:
```
Welcome! "examples/dummy.csv" has been loaded in an agate.csv.DictReader object named "reader".
>>> reader.next()
'DictReader' object has no attribute 'next'
```

csvpy: Change variable name and class name under --agate

---

csvkit/utilities/sql2csv.py

I noticed a bug when trying to use the DATE_FORMAT() function with a MySQL database using mysqlconnector dialect. This function requires % characters as format specifiers, see [MySQL documentation](http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_date-format). Previously using the mysqldb dialect I had no problems.
Compare the output from the following two commands:
```
sql2csv --db "mysql+mysqldb://...?charset=utf8" --query "select DATE_FORMAT(NOW(), '%c'), '%' AS '%'"
sql2csv --db "mysql+mysqlconnector://...?charset=utf8" --query "select DATE_FORMAT(NOW(), '%c'), '%' AS '%'"
```

Properly accept % in queries

---

AUTHORS.rst
CHANGELOG.rst
csvkit/utilities/csvsql.py
examples/foo1.csv
examples/foo2.csv
tests/test_utilities/test_csvsql.py

/cc @jpmckinney
Surfaces the new `create_if_not_exists` keyword arg in `agate-sql` (see
wireservice/agate-sql#25) as a command line flag.
For context, see #813.
By the way, is there some special development setup to develop csvkit and
agate-sql in tandem? (I was just developing agate-sql in the virtualenv XD)

Add --create-if-not-exists flag to csvsql

---

csvkit/utilities/csvgrep.py

This prevents an intermittent error when csvgrep exits:
sys:1: ResourceWarning: unclosed file \
<_io.TextIOWrapper name='foo.txt' mode='r' encoding='UTF-8'>

Close matchfile after reading it (#838)

---

CHANGELOG.rst
csvkit/utilities/csvgrep.py
tests/test_utilities/test_csvgrep.py

csvgrep accepts utf-8 arguments to the --match and --regex options

---

csvkit/utilities/csvgrep.py
docs/scripts/csvgrep.rst
tests/test_utilities/test_csvgrep.py

This simply adds a `-a / --any-match` flag to csvgrep to allow people to use the `any_match` functionality of the FilteringCSVReader.
I noticed that the `any_match` arg has tests but isn't used anywhere, so I'm not sure whether or not it was intentionally left out of csvgrep, but I needed it for something I was working on so I figured I'd add a test and make a quick PR.
Thanks for building such a great set of tools, I use csvkit constantly!

Allow using any_match with csvgrep

---

MANIFEST.in

Otherwise, building the documentation from the PyPI tarball yields the following:
```
/<<PKGBUILDDIR>>/docs/changelog.rst:5: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: '../CHANGELOG.rst'.
/<<PKGBUILDDIR>>/docs/index.rst:90: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: '../AUTHORS.rst'.
```

Add missing files for docs to manifest

---

csvkit/utilities/csvsql.py
docs/scripts/csvsql.rst

The option is already [available](https://github.com/wireservice/agate-sql/blob/f46bffb9125c7d5b9d0b41628a111f0ee1d8dd16/agatesql/table.py#L220). This is just exposing it in csvsql. Also, we are just passing the value along to agate-sql. So I didn't think there is a need for new test.
Let me know what you think.

Adds chunk_size to csvsql options

---

.travis.yml
requirements-py2.txt
requirements-py3.txt
setup.py
tests/test_py2.py

This branch:
- adds test support for Python 3.5, 3.6
- removes the now-unsupported Python 2.6
- upgrades openpyxl to 2.2.5, which has no breaking changes from 2.2.0 but includes bugfixes
- fixes a couple errors in the tests (`IOError: file must be opened in binary mode`)

Fix travis build

---

requirements-py2.txt
tests/test_cleanup.py
tests/test_cli.py
tests/test_convert/test_convert.py
tests/test_grep.py
tests/test_utilities/test_csvjson.py
tests/test_utilities/test_csvstat.py
tests/utils.py

csvkit doesn't support Python 2.6, so there is no need to use unittest2
which sole purpose is to bring unittest from Python 3.* (and 2.7) to
2.6.
Compatibility between 2.7 and 3.* API is provided by six (which is
already requirement for csvkit).
Fixes #978

Remove unnecessary dependency on unittest2

---

csvkit/utilities/csvstack.py
tests/test_utilities/test_csvstack.py

In **csvstack**, an error occurred when combining the `--no-header-row` flag with either `--groups` or `--filenames`.
For example:
```sh
$ csvstack --filenames -H examples/dummy.csv examples/dummy2.csv --verbose
```
The expected (if funky) output is:
```
group,a,b,c
dummy.csv,a,b,c
dummy.csv,1,2,3
dummy2.csv,a,b,c
dummy2.csv,1,2,3
```
However, this error occurs:
```
Traceback (most recent call last):
File "/Users/dan/.pyenv/versions/3.8.5/bin/csvstack", line 11, in <module>
load_entry_point('csvkit', 'console_scripts', 'csvstack')()
File "/Users/dan/git/csvkit/csvkit/utilities/csvstack.py", line 100, in launch_new_instance
utility.run()
File "/Users/dan/git/csvkit/csvkit/cli.py", line 118, in run
self.main()
File "/Users/dan/git/csvkit/csvkit/utilities/csvstack.py", line 80, in main …
```

Fixed error when --no-header-row is combined with --groups/--filenames

---

docs/tricks.rst

Add crontab use case, where you need to pass the file through piping rather than as an argument to the input.
See https://github.com/wireservice/csvkit/issues/342 and https://github.com/wireservice/csvkit/issues/1138

Add crontab use case

---

CHANGELOG.rst
csvkit/utilities/csvjoin.py
csvkit/utilities/csvjson.py
csvkit/utilities/csvlook.py
csvkit/utilities/csvsort.py
csvkit/utilities/csvsql.py
csvkit/utilities/csvstat.py
csvkit/utilities/in2csv.py
tests/test_utilities/test_csvclean.py

I use `csvkit` a lot and absolutely love it. `csvkit` (and `csvstat` in particular) can be very slow on large CSVs, and I decided to look into it. I used [snakeviz](https://jiffyclub.github.io/snakeviz/) to poke around.
```bash
~/Code/csvkit (master) $ curl https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2020-financial-year-provisional/Download-data/annual-enterprise-survey-2020-financial-year-provisional-csv.csv > nz.csv
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 5743k  100 5743k    0     0   742k      0  0:00:07  0:00:07 --:--:--  924k
~/Code/csvkit (master) $ time csvstat nz.csv > before.txt
csvstat nz.csv > before.txt  24.07s user 0.20s system 98% cpu 24.591 …
```

Speedup `csvstat` by using a sniff-limit and faster `get_freq` implementation

---

csvkit/cli.py

Python 3 standard library has support LZMA decompression used in XZ format. Since LZMA library is not available for Python 2, an error is raised when trying to read .xz on Python 2.
Happy for any feedback.

Add support for .xz files in Python 3.

---

.github/workflows/ci.yml
AUTHORS.rst
CHANGELOG.rst
csvkit/utilities/csvsql.py
csvkit/utilities/csvstat.py
docs/scripts/csvstat.rst
tests/test_utilities/test_csvstat.py

This allows users to specify a different decimal %-format syntax.
Grouping of numbers can be optionally disabled.

Add decimal formatting to csvstat

---

.github/workflows/pypi.yml
MANIFEST.in

Resolves #1234
I tested via running the commands from `.github/workflows/pypi.yml` locally, and verified the man pages got included in my built tarball.

feat: build man pages on release

---

CHANGELOG.rst
csvkit/cli.py
tests/test_utilities/test_csvformat.py
tests/test_utilities/test_csvjoin.py
tests/test_utilities/test_csvsql.py
tests/test_utilities/test_csvstack.py

fix: Add glob, user dir and env var support on Windows

---

csvkit/utilities/csvsql.py

Sometimes SQL statements in the wild use custom delimiters, other than the standard semicolon `;`.
This change adds a new argument to `csvsql` that applies to queries supplied under `--query`, `--before-insert`, and `--after-insert`.

csvsql: Adds configurable SQL query delimiter.

---

CHANGELOG.rst
csvkit/cli.py
docs/scripts/csvcut.rst
man/csvcut.1
tests/test_cli.py
tests/test_utilities/test_csvcut.py

Fixes #1280.  It's my first PR, do tell me if I've done something wrong or if something is missing. :)

feat(csvcut): Make -C ignore unknown columns
